### PR TITLE
Rewrote README to include a bit more verbose documentation. Replaced rst with md.

### PR DESCRIPTION
**Pull request by kingllama**
Github supports MD better than RST.

### CODE REVIEW

**Comment by Christophe31** [comment]
As python project are often documented with sphinx, I used RST. But I understand your point, it's a shorter syntax. Nice feature the exception, but you didn't update the raise which have now an extra arg.

**Comment by Christophe31** [comment]
I fixed things like setup.py which was referring to the readme, the exception definition and call…
You should test more before making a pull request.

**Comment by Christophe31** [comment]
Hoo, the reason why I used rst come back to my mind: http://stackoverflow.com/a/26737258/267364

**Comment by kingllama** [comment]
Sorry, I didn't mean to commit the Exception with this (I think I screwed up my rebase when I switched to master). Thanks for putting up with it though. I'll submit another Pull with a fixed exception and some other functionality for that exception. Thanks!

**Comment by kingllama** [comment]
Oh and that's a completely valid reason for using rst. If I knew that I wouldn't have switched it.

**Comment by Christophe31** [comment]
I already fixed the exception.

**Pull request merged**
